# Generated by Django 2.2 on 2021-05-28 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TV_shows_app', '0002_auto_20210528_0349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='show',
            name='release_date',
            field=models.DateField(blank=True, null=True, verbose_name='Release Date(YYYY/mm/dd)'),
        ),
    ]
